/*
 * Falanxia Moderatrix.
 *
 * Copyright (c) 2010 Falanxia (http://falanxia.com)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.falanxia.moderatrix.skin {
	import com.falanxia.moderatrix.enums.*;
	import com.falanxia.moderatrix.interfaces.*;
	import com.falanxia.utilitaris.enums.*;



	/**
	 * Container skin.
	 *
	 * Container skin to be used with the Container widget.
	 *
	 * @author Vaclav Vancura @ Falanxia a.s. <vaclav@falanxia.com>
	 * @author Falanxia (<a href="http://falanxia.com">falanxia.com</a>, <a href="http://twitter.com/falanxia">@falanxia</a>)
	 * @since 1.0
	 */
	public class ContainerSkin extends Skin implements ISkin {


		protected var _hAlign:String;
		protected var _vAlign:String;
		protected var _paddingTop:Number;
		protected var _paddingBottom:Number;
		protected var _paddingLeft:Number;
		protected var _paddingRight:Number;

		private var oldHAlign:String;
		private var oldVAlign:String;
		private var oldPaddingTop:Number;
		private var oldPaddingBottom:Number;
		private var oldPaddingLeft:Number;
		private var oldPaddingRight:Number;



		/**
		 * Constructor.
		 * ID is autogenerated if it's empty
		 * @param id Skin ID (optional)
		 */
		public function ContainerSkin(id:String = null) {
			super(SkinType.CONTAINER, id);

			_hAlign = Align.LEFT;
			_vAlign = Align.TOP;
			_paddingTop = 0;
			_paddingBottom = 0;
			_paddingLeft = 0;
			_paddingRight = 0;
		}



		/**
		 * Destroys the ContainerSkin instance and frees it for GC.
		 */
		override public function destroy():void {
			super.destroy();

			_hAlign = null;
			_vAlign = null;

			oldHAlign = null;
			oldVAlign = null;
		}



		/**
		 * Parse config Object.
		 * @param value Config Object
		 */
		override public function parseConfig(value:Object):void {
			super.parseConfig(value);

			oldHAlign = _hAlign;
			oldVAlign = _vAlign;
			oldPaddingTop = _paddingTop;
			oldPaddingBottom = _paddingBottom;
			oldPaddingLeft = _paddingLeft;
			oldPaddingRight = _paddingRight;

			if(value.hAlign != undefined) _hAlign = value.hAlign;
			if(value.vAlign != undefined) _vAlign = value.vAlign;
			if(value.paddingTop != undefined) _paddingTop = value.paddingTop;
			if(value.paddingBottom != undefined) _paddingBottom = value.paddingBottom;
			if(value.paddingLeft != undefined) _paddingLeft = value.paddingLeft;
			if(value.paddingRight != undefined) _paddingRight = value.paddingRight;
		}



		/**
		 * Revert config to the last known state.
		 */
		override public function revertConfig():void {
			super.revertConfig();

			_hAlign = oldHAlign;
			_vAlign = oldVAlign;
			_paddingTop = oldPaddingTop;
			_paddingBottom = oldPaddingBottom;
			_paddingLeft = oldPaddingLeft;
			_paddingRight = oldPaddingRight;
		}



		/**
		 * Get horizontal alignment.
		 * @return Horizontal alignment
		 * @see Align
		 */
		public function get hAlign():String {
			return _hAlign;
		}



		/**
		 * Set horizontal alignment.
		 * @param value Horizontal alignment
		 * @see Align
		 */
		public function set hAlign(value:String):void {
			_hAlign = value;
		}



		/**
		 * Get vertical alignment.
		 * @return Vertical alignment
		 * @see Align
		 */
		public function get vAlign():String {
			return _vAlign;
		}



		/**
		 * Set vertical alignment.
		 * @param value vertical alignment
		 * @see Align
		 */
		public function set vAlign(value:String):void {
			_vAlign = value;
		}



		/**
		 * Get top padding.
		 * @return Top padding
		 */
		public function get paddingTop():Number {
			return _paddingTop;
		}



		/**
		 * Set top padding.
		 * @param value Top padding
		 */
		public function set paddingTop(value:Number):void {
			_paddingTop = value;
		}



		/**
		 * Get bottom padding.
		 * @return Bottom padding
		 */
		public function get paddingBottom():Number {
			return _paddingBottom;
		}



		/**
		 * Set bottom padding.
		 * @param value Bottom padding
		 */
		public function set paddingBottom(value:Number):void {
			_paddingBottom = value;
		}



		/**
		 * Get left padding.
		 * @return Left padding
		 */
		public function get paddingLeft():Number {
			return _paddingLeft;
		}



		/**
		 * Set left padding.
		 * @param value Left padding
		 */
		public function set paddingLeft(value:Number):void {
			_paddingLeft = value;
		}



		/**
		 * Get right padding.
		 * @return Right padding
		 */
		public function get paddingRight():Number {
			return _paddingRight;
		}



		/**
		 * Set right padding.
		 * @param value Right padding
		 */
		public function set paddingRight(value:Number):void {
			_paddingRight = value;
		}
	}
}
